### ISSUE TITLE
question 1 of [number] could be made to increase if a question is added mid session

### ISSUE THREAD

**Issue by christopheralcock** [zlahham/live-voting#174]
at the moment if the speaker adds a question mid-event, they'll end up with, say, question 5 of 4. if the audience reloads their page it will fix, and that's not too much to ask, but we could include the total number of questions in the json if we wanted to

**Comment by Yorkshireman** [comment]
I think this is worthy of our time.

**Comment by Yorkshireman** [comment]
I think this is worthy of our time.
